# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
jobs:    
  torelease:
    runs-on: ubuntu-latest
    steps:
      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        with:
          name: 发布名称
#           tag_name: ${{ steps.tag.outputs.release_tag }}
#           body_path: release.txt
#           files: ${{ env.FIRMWARE }}/*
